# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "development" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: ['20.x']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup SSL certificate
      run: |
        $certContent = [System.Convert]::FromBase64String("${{ secrets.SSL_CERT_BASE64 }}")
        [System.IO.File]::WriteAllBytes("${{ github.workspace }}/config/ca-certificate.crt", $certContent)
        echo "SSL_CERT_PATH=config/ca-certificate.crt" >> $GITHUB_ENV
      shell: pwsh
    - name: clean install
      run: npm ci
    - run: npm run build --if-present
    - name: Run tests with coverage
      run: npm run server-test
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_PORT: ${{ secrets.DB_PORT }}
      SSL_CERT_PATH: ${{ secrets.SSL_CERT_PATH }}
      SSL_CERT: ${{ secrets.SSL_CERT }}

